[phases.setup]
nixPkgs = [
    "dejavu_fonts",
    "fontconfig"
]

[phases.install]
commands = [
    # Link fonts from Nix store to system location
    "ln -sf ${pkgs.dejavu_fonts}/share/fonts/truetype/dejavu /usr/share/fonts/truetype/",
    "fc-cache -f -v"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300"
