[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "fc-cache -f -v",
    "test -f /app/start.sh && echo 'Start script exists' || echo 'Missing start script'",
    "ls -l /app"
]

[phases.start]
cmd = "/app/start.sh"
