[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "fc-cache -f -v -y"  # Force rebuild font cache
]

[phases.start]
cmd = "./start.sh"
