[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "fc-cache -f -v",
    # Ensure script is copied to final location
    "cp $out/app/start.sh . && chmod +x start.sh"
]

[phases.start]
cmd = "./start.sh"
