[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "fc-cache -f -v",
    # Ensure Python environment is activated
    "echo 'PYTHONPATH=${pythonEnv}/${pythonEnv.sitePackages}' >> .env"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300 --bind 0.0.0.0:$PORT"
