[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "fc-cache -f -v",
    "ln -s ${pkgs.dejavu_fonts}/share/fonts/truetype/dejavu /app/fonts"
]

[phases.start]
cmd = "start-app"
