[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "dejavu_fonts",
  "fontconfig",
  "zlib",
  "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
  "pip install --no-cache-dir -r requirements.txt"
  "fc-cache -f -v",
  "ln -sf /nix/store/*-dejavu-fonts-*/share/fonts/truetype/dejavu /app/fonts"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300 --bind 0.0.0.0:$PORT"
