[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.gunicorn",
    "dejavu_fonts",
    "fontconfig"
]

[phases.install]
commands = [
    "pip install -r requirements.txt",
    "fc-cache -f -v"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300 --bind 0.0.0.0:$PORT"
