[phases.setup]
nixPkgs = [
    "python311",
    "dejavu_fonts",
    "fontconfig",
    "zlib",
    "stdenv.cc.cc.lib"
]

[phases.install]
commands = [
    "mkdir -p /app/fonts",
    "ln -sf /nix/store/*-dejavu-fonts-*/share/fonts/truetype/dejavu/* /app/fonts/",
    "fc-cache -f -v"
]

[phases.start]
cmd = "start-app"
