[phases.setup]
nixPkgs = [
    "dejavu_fonts",
    "fontconfig"
]

[phases.install]
commands = [
    # Get font path using nix-shell and copy fonts
    "nix-shell -p dejavu_fonts --run 'cp -r $out/share/fonts/truetype/dejavu /usr/share/fonts/truetype/'",
    
    # Verify installation
    "ls -l /usr/share/fonts/truetype/dejavu",
    
    # Rebuild font cache
    "fc-cache -f -v"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300"
