[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "dejavu_fonts",
    "fontconfig",
    "gunicorn"
]

[phases.install]
commands = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "fc-cache -f -v"
]

[phases.start]
cmd = "gunicorn main:app --timeout 300 --bind 0.0.0.0:$PORT"
